### ISSUE TITLE
Expected Lua table error with new transclusion and link functions

### ISSUE THREAD

**Issue by kai-coo-per** [kentookura/forester.nvim#13]
MacOS version: Ventura 13.4
forester version --3.0.1
neovim version --0.9.5

Upon calling the commands for transclude_new or link_new, this error surfaces. 

Error executing vim.schedule lua callback: ...im/site/pack/packer/start/forester.nvim/lua/forester.lua:162: Expected lua
 table                                                                                                                  
stack traceback:                                                                                                        
        [C]: in function 'nvim_buf_set_text'                                                                            
        ...im/site/pack/packer/start/forester.nvim/lua/forester.lua:162: in function 'put'                              
        ...im/site/pack/packer/start/forester.nvim/lua/forester.lua:171: in function 'callback'                         
        ...ack/packer/start/forester.nvim/lua/forester/bindings.lua:41: in function <...ack/packer/start/forester.nvim/l
ua/forester/bindings.lua:40>

New from template gives:

Error executing vim.schedule lua callback: .../packer/start/dressing.nvim/lua/dressing/select/init.lua:33: items: expect
ed list-like table, got table: 0x0108efccc8                                                                             
stack traceback:                                                                                                        
        [C]: in function 'error'                                                                                        
        vim/shared.lua: in function 'validate'                                                                          
        .../packer/start/dressing.nvim/lua/dressing/select/init.lua:33: in function ''                                  
        vim/_editor.lua: in function <vim/_editor.lua:0>

I didn't have the new from template error before the recent updates to this package.

**Comment by kentookura** [comment]
These are not yet implemented. I updated the README to reflect that fact. I'll be setting up some CI and testing to make sure the repo is always in a consistent state. Sorry for any inconvenience.
