### ISSUE TITLE
bug: ForestNew throws an error and key bindings don't work but ForestOpen does not

### ISSUE THREAD

**Issue by kai-coo-per** [kentookura/forester.nvim#2]
### Did you check docs and existing issues?

- [X] I have read all the plugin docs
- [X] I have searched the existing issues
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.9.4

### Operating system/version

MacOS 13.4

### Describe the bug

Neither :ForestNew command, nor its key bindings are working properly on my machine. However, :Forestpen is, and its key bindings are just fine. When activating :ForestNew, the "Select one of" window pops up but then this error appears. Not sure what to do about this.

Error executing vim.schedule lua callback: ...im/site/pack/packer/start/forester.nvim/lua/forester.lua:20: attempt to co
ncatenate a nil value                                                                                                   
stack traceback:                                                                                                        
        ...im/site/pack/packer/start/forester.nvim/lua/forester.lua:20: in function <...im/site/pack/packer/start/forest
er.nvim/lua/forester.lua:19>

### Steps To Reproduce

1. Call :ForestNew
2. Type in desired name of tree

### Expected Behavior

Tree generation and to take me to that tree.

**Comment by kentookura** [comment]
What version of forester are you on? This feature made use of a feature I had implemented on my branch of forester, which was only merged yesterday. Please try again using the latest version of forester.

**Comment by kai-coo-per** [comment]
I'm on forester 2.5.1

**Comment by kentookura** [comment]
How did you install it? If you installed it with opam, then the newest features are not part of your release.

**Comment by kai-coo-per** [comment]
Yes I installed it with opam. I guess I need to do something else?

**Comment by kentookura** [comment]
This commit is what added the feature: 
https://git.sr.ht/~jonsterling/ocaml-forester/commit/faad8193b27db19e191e22cdecccdcb2492b8adb
I just saw that Jon released forester 3.0.0 yesterday, the feature is part of that release

**Comment by dannypsnl** [comment]
And you should update a more recently version due to a bug just fixed a few hours ago XD.

**Comment by kentookura** [comment]
I also fixed the typo in the command name

**Comment by kai-coo-per** [comment]
Just updated forester to the latest version. Now the "Select one of" box is not empty and is populated with an already present tree prefix, but I'm having the same issue as before.

**Comment by kentookura** [comment]
What is the output of the command `forester new --prefix foo --dir trees`?

**Comment by kai-coo-per** [comment]
So that specific command returns an error: 

`
forester: required option --dest is missing
Usage: forester new [OPTION]…
Try 'forester new --help' or 'forester --help' for more information.
`

**Comment by kentookura** [comment]
I hadn't updated the plugin to use the new version of forester. Feel free to reopen if there are any issues.
