### ISSUE TITLE
Implement spell queries

### ISSUE THREAD

**Issue by chezbgone** [kentookura/forester.nvim#20]
Tree-sitter has queries for whether a node should be spell checked or not:
https://github.com/nvim-treesitter/nvim-treesitter/blob/master/CONTRIBUTING.md#non-highlighting-captures

I think it would be nice if `\p` nodes had this query, as they are often text. I'm not sure how this interacts with math environments inside them though.

**Comment by kentookura** [comment]
All we need to do for this is write a query that matches the text that we want. The query mechanism easily takes care of your concern with environments we don't want to highlight.

I should also get around to highlighting math environments via embedded syntax.

**Comment by kentookura** [comment]
Try it out in a buffer by running `:setlocal spell spelllang=en_us`
