### ISSUE TITLE
Don't rely on user config for getting tree directories

### ISSUE THREAD

**Issue by kentookura** [kentookura/forester.nvim#26]
I think we should add a function which recursively scans directories for trees relative to the working directory. The current setup is annoying to work with, since I need to propagate the user config deep into the plugin.

**Comment by dannypsnl** [comment]
Since now forester has configuration, should be able to scan upper to find a config file?

**Comment by kentookura** [comment]
Yeah, I started looking for that function today. I remember it's somewhere either in plenary or included with vim... coming soon

**Comment by kentookura** [comment]
```lua
local function find_config(filename)
  return vim.fn.findfile(filename, ".;")
end

local function find_default_config()
  return vim.fn.findfile("forest.toml", ".;")
end

local function get_file_contents(filename)
  return table.concat(vim.fn.readfile(filename), "\n")
end

local get_tree_dirs = function(config)
  local text = get_file_contents(config)
  local parser = vim.treesitter.get_string_parser(text, "toml")

  local query = vim.treesitter.query.parse(
    "toml",
    [[(document
        (table
          (pair
            (bare_key) @key
            (array (string) @dir))))
    ]]
    -- (bare_key) @key (#eq? @key "trees")
    -- (array (string) @tree_dir ))))
  )

  local dirs = {}
  for id, node in query:iter_captures(parser:parse()[1]:root(), 0) do
    local name = query.captures[id]
    local dir = vim.treesitter.get_node_text(node, text)
    table.insert(dirs, { dir, name })
  end
  return dirs
end
```
This is what I have so far. For some reason I can't get the query to work properly. using the uncommented line gives nothing.

**Comment by kentookura** [comment]
figured it out 👍

**Comment by kentookura** [comment]
Sorry it's taking so long to release the update. I need to figure out a way to ergonomically switch between different config files in neovim, and in general need to polish a lot of stuff

**Comment by dannypsnl** [comment]
I'm fine to have a rough version for now.

**Comment by kentookura** [comment]
the `unreleased` branch contains all of the work. You can search for hardcoded ocurrences of `forest.toml` in the codebase to see where I still need to work some stuff out.

**Comment by dannypsnl** [comment]
<img width="1114" alt="image" src="https://github.com/kentookura/forester.nvim/assets/22004511/f774f0a2-1abd-4fda-adb6-b0e83b6cdb31">

I tried install it like
```lua
{
    "nvim-treesitter/nvim-treesitter",
    opts = {
      ensure_installed = {
        -- ...
        "yaml",
        "toml",
      },
    }
}          
```
maybe I misunderstood something.

**Comment by kentookura** [comment]
I ran into this too, I fixed it by running `:TSInstall toml`
